### PR TITLE
Generating jsPlumb extra js dist files without version number

### PR DESCRIPTION
**Pull request by carloschneider**
#331

### CODE REVIEW

**Comment by enapupe** [comment]
Thanks for that! I think that solution solves the issue for both sides.. well done!

**Comment by jpmckearin** [comment]
Looking forward to this being merged in.

**Comment by sporritt** [comment]
@koppor @jpmckearin @enapupe @carloschneider 

So the common thread with this and the various related issues is the notion that if you use bower for dependencies and you want to upgrade your version of jsPlumb, it is not as convenient as you would like. Is that correct?  Does anyone feel like jotting down in point form the steps they have to follow?

**Comment by enapupe** [comment]
That is correct, not only because of convenience, also because of established standards..
I believe that most people that uses bower and starts using jsPlumb, eventually will come here asking the same question.

**Comment by jpmckearin** [comment]
For bower standards, please see this document. http://bower.io/docs/creating-packages/

image

**Comment by sporritt** [comment]
i don't want to see bower standards. i want to someone to list in point form what their specific problem is.

**Comment by enapupe** [comment]
- front end project gets a release tag
- ti team fetches the repo and run build
- build process runs bower update
- meanwhile jsPlumb gets an update and the file name changes
- front end project has a 404 link to a js file
- build process fails (compiles the bundle without jsPlumb)


what happens if jsPlumb follows the standard:
- ...
- meanwhile jsPlumb gets an update fixing a important bug
- front end project gets a free fix without even noticing
- ...


Is that all?

**Comment by koppor** [comment]
My main issue is experimenting with different versions: If I include jsPlumb in three files and I change the version of jsPlumb, I have two change all three of them. What if I want to track down when a certain behavior changed (like #165)? Then I have to copy the new version of jsPlumb in and change three files. If that version still has that issue, I have to pick another version and change three files again. Until I identified the right version. - If jsPlumb had the same filename for different versions, I only had to replace the js file without changing the three files.

**Comment by sporritt** [comment]
That's great, thanks.  Couple of questions:

- In the first case it seems you are deploying each JS file individually?  That is correct?  You're not concatenating and minifiying everything?

- You also seem to be referencing the latest version of jsplumb automatically. Why would you do this? it isn't a good practise to blindly import the latest of anything. You should always import a version that you know works. Getting a "free fix without even noticing" is not at all a good idea.  

"The standard" as you refer to it is just Bower's standard.  Not every package manager works this way. Opinions on Bower vary; mine is that you should something that does not mistakenly conflate the concepts of version control with package management, such as npm.


Does anyone else want to list in point form what their specific problem is?

**Comment by sporritt** [comment]
@koppor what three files are you talking about here?

**Comment by enapupe** [comment]
The IT guys run the build procedure which concatenates all bower's referenced file into a single package. That files are referenced in a HTML file, so the script's path must be **precise**.

About the version I know it works, you are half right. That is where *semver* should ease things, I know it's not 100% but aims to be - a minor version is not supposed to break things. 

I think that many people maintain a exclusive repository for bower is to avoid this kind of issue. Example: https://github.com/angular/bower-angular

**Comment by sporritt** [comment]
I was leaning towards that solution in fact - a separate `bower-jsplumb` repository. Thing is for me it's just something else to manage.

**Comment by enapupe** [comment]
Yeah, that's sad. So why is so important to keep things as they are now?

Another thing to consider is how much of jsPlumb users are also bower users..

**Comment by sporritt** [comment]
That's sad?  Pardon?

**Comment by enapupe** [comment]
It is sad have to keep another repo.. We should DRY.
I think this article is interesting, an overview about today's fe tooling http://ashleynolan.co.uk/blog/frontend-tooling-survey-2015-results

**Comment by koppor** [comment]
@sporritt In my setting, It's one jsp for editing a graph, one jsp for rendering the graph only and a test html file with a minimal test.

**Comment by sporritt** [comment]
https://github.com/jsplumb/bower-jsplumb

**Comment by sporritt** [comment]
closing. built js doesnt have the version number now.  but that still does not mean that anyone should trust a library author and blindly enable "non breaking" changes via their semver specification in package.json.

**Pull request closed without merging**
