### PR TITLE
add rank for _initDropTarget's dropOptions

### PR DESCRIPTION
**Pull request by JomppeTuominen**
Add rank parameter for "normal" endpoints as well, related to https://github.com/jsplumb/katavorio/issues/32

### CODE REVIEW

**Comment by sporritt** [comment]
thanks for this. what would it mean for the setup that there are nodes inside a group and the group has endpoints? the group gets -1 by default, the node gets nothing, and the group endpoints get 0. so they would take precedence over any nodes?

**Comment by JomppeTuominen** [comment]
Did you check the fiddle in the linked issue (https://github.com/jsplumb/jsplumb/issues/795)? It hopefully makes the issue more clear.

**Comment by sporritt** [comment]
yes i saw the fiddle. i am asking about the larger impact of this change.

**Comment by JomppeTuominen** [comment]
Sorry, I don't quite understand your question, but I would use it like this:

The group and its endpoints get rank 1, the nodes inside the group and their endpoints get rank 2 (or any number that is larger than group's rank). If I don't give rank to endpoints, and drop a connection on an endpoint, the connection is created to the element whose rank is higher, and not to the endpoint.

I'm just trying to achieve a scenario where the topmost shape (or endpoint) would get precedence over others. 
Would you prefer if endpoints got no rank if none was passed?

**Comment by sporritt** [comment]
I'm just trying to ensure that the out of the box experience offers the fewest surprises for the most number of people. The fiddle you provided exhibited some surprising behaviour: it felt intuitive that the endpoint should take precedence over the body of the div underneath, but it did not. So your fix, in this case, definitely solves that particular issue.  I just need to be sure that it doesn't result in surprises popping up elsewhere, and also that I am satisfied the documentation makes clear to everyone what's going on. So I will look at this at some stage soon, probably not for a few days though. Thanks again.

**Comment by JomppeTuominen** [comment]
Alright, thanks.

**Pull request closed without merging**
