### PR TITLE
minor updates to Typescript definition file

### PR DESCRIPTION
**Pull request by RonNewcomb**
several minor updates to Typescript definition file, notably drag-drop stuff

### CODE REVIEW

**Comment by Schlesiger** [comment]
Thank you! The drag options in particular stand out as I had also started updating them.

**Comment by sporritt** [comment]
whoops..i.left this comment on the commit instead of here...

thanks. for the moment i am going to hold off merging this as there are a few adjustments i'd like to make, as well as pulling a few things in from the Toolkit edition types. i will update the PR again shortly.

**Comment by susox** [comment]
any estimation on when this PR will be merged?

**Comment by Schlesiger** [comment]
Are these changes merged with the latest updates?

**Comment by sporritt** [comment]
no. most of this PR is stale now; bits of it were added manually, but  the Endpoint config stuff was not exactly how I wanted to do the typings.  the 'Katavorio_DragEventOptions' definition will make it into the next release, perhaps renamed.

**Pull request closed without merging**
