### PR TITLE
Update index.d.ts

### PR DESCRIPTION
**Pull request by SunoAries**
add group relative declare

### CODE REVIEW

**Comment by sporritt** [comment]
thanks for this.  a few notes:

- `connections` on a Group is not a single connection, it's an array like this:

```
this.connections = { source:[], target:[], internal:[] };
```

so it's like:

```
connections:{ source:Array<Connection>, target:Array<Connection>, internal:Array<Connection> };
```

- `getMembers()` returns  `Array<ElementRef>`. What is `ElementGroupRef` ?

- most of the methods that take a group as argument, with the exception of `getGroup`, support `Group|string` as the type of the group argument. I know the existing js doc does not always reflect this.

- The js doc also uses the `SomeType[]` syntax to reference arrays. I've been trying to switch jsPlumb to use the `Array<SomeType>` syntax instead.

- `id` should be optional on `GroupOptions`

- `getAnchor` should return an `AnchorSpec`

- `overrideDrop` in `Group` should include the args (it could be overridden) :

```
overrideDrop:(el?:ElementRef, targetGroup?:Group) => boolean
```

**Comment by SunoAries** [comment]
Thanks for note, I have commit another fix

**Comment by sporritt** [comment]
great, thanks. i will do a new release later today.

**Comment by sporritt** [comment]
2.15.1 was just released.

**Pull request merged**
