### PR TITLE
#Issue 1135 Set the dragging endpoint follow the cursor when scroll

### PR DESCRIPTION
**Pull request by MornMartin**

### CODE REVIEW

**Comment by MornMartin** [comment]
Issue: #1135

**Comment by sporritt** [comment]
thanks for this. were you able to reproduce the issue in a failing unit test?

**Comment by sporritt** [comment]
...I can't reproduce this in a failing unit test, which bothers me, and also I'm not now even convinced that the unit test covering document scroll during a connection drag is actually testing anything.

**Comment by MornMartin** [comment]
> ...I can't reproduce this in a failing unit test, which bothers me, and also I'm not now even convinced that the unit test covering document scroll during a connection drag is actually testing anything.

I summed up the way to reproduce this issue in https://github.com/jsplumb/jsplumb/issues/1135#issuecomment-1181414306

**Comment by Mohamed-1810** [comment]
Could you please share me how you solved this?? I am stuck in this for nearly one week

**Pull request closed without merging**
