### PR TITLE
Add missing connector property to ConnectorParams object

### PR DESCRIPTION
**Pull request by abhirocks550**
Add connector property inside ConnectorParams object to specify the connection.

### CODE REVIEW

**Comment by sporritt** [comment]
thanks. but `connector` should, i think, be of type `ConnectorSpec`, shouldnt it?

**Comment by abhirocks550** [comment]
Yes, correct. I changed the type and added commit.

**Comment by sporritt** [comment]
cool, thanks!

**Comment by abhirocks550** [comment]
My first PR got merged in open source :-) Thanks :-) 👍

**Comment by abhirocks550** [comment]
Any update on releasing the above change?

**Comment by abhirocks550** [comment]
@sporritt Can you please release the above changes in the new version?

**Comment by abhirocks550** [comment]
Thanks :-) 👍

**Pull request merged**
