### PR TITLE
Fix TypeScript definition for optional attributes in EndpointOptions

### PR DESCRIPTION
**Pull request by Howarto**
All EndpointOptions attributes are optionals. I fixed their TypeScript definition.

### CODE REVIEW

**Comment by Howarto** [comment]
@sporritt Now seems that it works well 👍

**Comment by phroggyy** [comment]
This looks good. The current incorrect typings are currently causing us a lot of headache so I'd love to see this merged

**Comment by sporritt** [comment]
i'll try to take a look at this shortly

**Comment by sporritt** [comment]
@Howarto thanks for this

**Pull request merged**
