### PR TITLE
Add missing functions to the TypeScript definitions file

### PR DESCRIPTION
**Pull request by mprahl**
These are functions I'd like to use in TypeScript but aren't available in the definitions file.

### CODE REVIEW

**Comment by sporritt** [comment]
thanks for this, i added these manually. they're in master now.

**Comment by mprahl** [comment]
@sporritt why was the definition for `deleteEveryConnection` not added?

**Comment by sporritt** [comment]
i though it had been

it has now

**Comment by mprahl** [comment]
@sporritt thanks for incorporating the changes but I'm confused as to why you just didn't merge my PR. You incorporated the same changes I proposed but yet you made separate commits without attributing git authorship to me.

**Comment by sporritt** [comment]
the master copy of that file is actually in the toolkit repository and gets copied wholesale into the community edition from time to time. i can see what you are saying regarding git authorship but i didn't really think a couple of lines in a typings file would be a big deal.

**Comment by mprahl** [comment]
@sporritt I see. Thanks for incorporating the changes.

**Pull request closed without merging**
