### PR TITLE
Calculating parentOffset only when needed & updated getAttribute function to check if element has an attribute or not

### PR DESCRIPTION
**Pull request by ankushbansal89**
Change#1: In dom-adapter.js, parentOffset was getting calculated even if it was not needed under some scenarios. This was causing unnecessary layout thrashing. To avoid it, parentOffset is now calculated only when it is needed.

Changes#2: Console error was thrown when getAttribute is called with an attribute and element didn't have that attribute defined. Added a hasAttribute check before calling getAttribute on the element.

### CODE REVIEW

**Comment by sporritt** [comment]
thanks!

can you show me the console error from `getAttribute`? i have never seen this. the method is declared to return null or an empty string when called for an attribute that does not exist:

https://developer.mozilla.org/en-US/docs/Web/API/Element/getAttribute

**Comment by sporritt** [comment]
@ankushbansal89 i'd like to merge this, i think, but i would like to see the error you reported. could you paste a screenshot with the stack trace?

**Comment by ankushbansal89** [comment]
Thank you @sporritt for the quick reply!! Here is the stack trace that I was seeing:

 Error: Invalid attribute "id" for [object:vm <component name> (94)]. Instead access the public property with `element.id;`.
    at root.jsPlumbInstance.getAttribute (jsplumb.js:5101)
    at root.jsPlumbInstance._getId [as getId] (jsplumb.js:3272)
    at _oneLevel (jsplumb.js:4890)
    at _oneLevel (jsplumb.js:4896)
    at DragManager.register (jsplumb.js:4901)
    at _initDraggableIfNecessary (jsplumb.js:3009)
    at HTMLDivElement.eval (jsplumb.js:3640)

This could be a consequence of javascript framework that I am using. The framework uses web components and virtual dom. IMO, adding hasAttribute check has no side effect. I ran all the unit tests after my changes and all the tests are passing. However, if you think otherwise, then I can revert hasAttribute changes.

**Comment by sporritt** [comment]
i'd rather not include the `hasAttribute` test. it's unnecessary according to the spec of getAttribute.

where do you think this `Error: Invalid attribute "id" for [object:vm (94)]. Instead access the public property with element.id;` message is coming from?

**Comment by ankushbansal89** [comment]
I have updated the PR and removed hasAttribute changes from it.

**Comment by sporritt** [comment]
can you tell me where you think that error message is coming from, though? presumably with the changes you made you are still seeing that message? and therefore, presumably, the ID is not being resolved in your case?

**Comment by ankushbansal89** [comment]
I did some digging and found out that this error is thrown by framework I am using. As a solution, I added Id to my elements, so that error is not thrown.

**Comment by sporritt** [comment]
given there's now unnecessary commits in this branch i'd rather start over with a clean one. @ankushbansal89 i can just add the relevant code for the parent offset calculations, but recently someone complained to me about not merging their PR, despite the fact that the code they wanted ended up in the project. i suppose they also wanted the statistics. so it's up to you - if you want to cut a new branch and change only those two parent offset things i will merge that PR. otherwise i will just add the code myself and make a note of your contribution in the changelog.  can you let me know? thanks.

**Comment by ankushbansal89** [comment]
As long as JSplumb is improving, I don't mind who makes the changes. To make it easier, I have created a new pull request for these changes. I will close this one. 
Here is the link to the new PR: https://github.com/jsplumb/jsplumb/pull/769

Thank you @sporritt!!

**Pull request closed without merging**
